In [101]:
import pandas as pd
import scipy
from scipy import stats
from scipy import linalg
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
import scipy.stats as ss
import pingouin as pg
from scipy.stats import levene
from statsmodels.stats.multicomp import (pairwise_tukeyhsd,
                                         MultiComparison)
from statsmodels.formula.api import ols
from statsmodels.stats.anova import anova_lm

import statsmodels.api as sm
import statsmodels.formula.api as smf

import scikit_posthocs as sp

In [61]:
df = pd.read_csv('/Users/siarheimasliankou/Documents/Work/DA_Practice/Statistics/Task_7/cars.csv')

In [62]:
df['company'] = df['CarName'].apply(lambda x: x.split()[0])

In [63]:
df = df.drop(columns=['CarName', 'car_ID'])

In [64]:
df.company.nunique()

28

In [65]:
df['company'] = df['company'].str.lower()
df['company'] = df['company'].replace({'maxda':'mazda', 'porcshce':'porsche', 'toyouta':'toyota', 'vokswagen':'volkswagen', 'vw':'volkswagen'})

In [66]:
df.company.value_counts()

company
toyota         32
nissan         18
mazda          17
mitsubishi     13
honda          13
volkswagen     12
subaru         12
peugeot        11
volvo          11
dodge           9
buick           8
bmw             8
audi            7
plymouth        7
saab            6
porsche         5
isuzu           4
jaguar          3
chevrolet       3
alfa-romero     3
renault         2
mercury         1
Name: count, dtype: int64

In [67]:
df

,symboling,fueltype,aspiration,doornumber,carbody,drivewheel,enginelocation,wheelbase,carlength,carwidth,...,fuelsystem,boreratio,stroke,compressionratio,horsepower,peakrpm,citympg,highwaympg,price,company
0,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,mpfi,3.47,2.68,9.0,111,5000,21,27,13495.0,alfa-romero
1,3,gas,std,two,convertible,rwd,front,88.6,168.8,64.1,...,mpfi,3.47,2.68,9.0,111,5000,21,27,16500.0,alfa-romero
2,1,gas,std,two,hatchback,rwd,front,94.5,171.2,65.5,...,mpfi,2.68,3.47,9.0,154,5000,19,26,16500.0,alfa-romero
3,2,gas,std,four,sedan,fwd,front,99.8,176.6,66.2,...,mpfi,3.19,3.40,10.0,102,5500,24,30,13950.0,audi
4,2,gas,std,four,sedan,4wd,front,99.4,176.6,66.4,...,mpfi,3.19,3.40,8.0,115,5500,18,22,17450.0,audi
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,-1,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,mpfi,3.78,3.15,9.5,114,5400,23,28,16845.0,volvo
201,-1,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.8,...,mpfi,3.78,3.15,8.7,160,5300,19,25,19045.0,volvo
202,-1,gas,std,four,sedan,rwd,front,109.1,188.8,68.9,...,mpfi,3.58,2.87,8.8,134,5500,18,23,21485.0,volvo
203,-1,diesel,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,idi,3.01,3.40,23.0,106,4800,26,27,22470.0,volvo
204,-1,gas,turbo,four,sedan,rwd,front,109.1,188.8,68.9,...,mpfi,3.78,3.15,9.5,114,5400,19,25,22625.0,volvo

In [68]:
selected_columns = ['company', 'fueltype', 'aspiration', 'carbody', 'drivewheel', 'wheelbase', 'carlength', 'carwidth', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 'boreratio', 'horsepower', 'price']
up_df = df[selected_columns]

up_df

,company,fueltype,aspiration,carbody,drivewheel,wheelbase,carlength,carwidth,curbweight,enginetype,cylindernumber,enginesize,boreratio,horsepower,price
0,alfa-romero,gas,std,convertible,rwd,88.6,168.8,64.1,2548,dohc,four,130,3.47,111,13495.0
1,alfa-romero,gas,std,convertible,rwd,88.6,168.8,64.1,2548,dohc,four,130,3.47,111,16500.0
2,alfa-romero,gas,std,hatchback,rwd,94.5,171.2,65.5,2823,ohcv,six,152,2.68,154,16500.0
3,audi,gas,std,sedan,fwd,99.8,176.6,66.2,2337,ohc,four,109,3.19,102,13950.0
4,audi,gas,std,sedan,4wd,99.4,176.6,66.4,2824,ohc,five,136,3.19,115,17450.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,volvo,gas,std,sedan,rwd,109.1,188.8,68.9,2952,ohc,four,141,3.78,114,16845.0
201,volvo,gas,turbo,sedan,rwd,109.1,188.8,68.8,3049,ohc,four,141,3.78,160,19045.0
202,volvo,gas,std,sedan,rwd,109.1,188.8,68.9,3012,ohcv,six,173,3.58,134,21485.0
203,volvo,diesel,turbo,sedan,rwd,109.1,188.8,68.9,3217,ohc,six,145,3.01,106,22470.0
204,volvo,gas,turbo,sedan,rwd,109.1,188.8,68.9,3062,ohc,four,141,3.78,114,22625.0

In [69]:
numeric_df = up_df[['wheelbase', 'carlength', 'carwidth', 'curbweight', 'enginesize', 'boreratio', 'horsepower', 'price']]

correlation_matrix = numeric_df.corr()

price_correlation = correlation_matrix['price']
price_correlation.round(2)

wheelbase     0.58
carlength     0.68
carwidth      0.76
curbweight    0.84
enginesize    0.87
boreratio     0.55
horsepower    0.81
price         1.00
Name: price, dtype: float64

In [70]:
correlation_matrix

,wheelbase,carlength,carwidth,curbweight,enginesize,boreratio,horsepower,price
wheelbase,1.000000,0.874587,0.795144,0.776386,0.569329,0.488750,0.353294,0.577816
carlength,0.874587,1.000000,0.841118,0.877728,0.683360,0.606454,0.552623,0.682920
carwidth,0.795144,0.841118,1.000000,0.867032,0.735433,0.559150,0.640732,0.759325
curbweight,0.776386,0.877728,0.867032,1.000000,0.850594,0.648480,0.750739,0.835305
enginesize,0.569329,0.683360,0.735433,0.850594,1.000000,0.583774,0.809769,0.874145
boreratio,0.488750,0.606454,0.559150,0.648480,0.583774,1.000000,0.573677,0.553173
horsepower,0.353294,0.552623,0.640732,0.750739,0.809769,0.573677,1.000000,0.808139
price,0.577816,0.682920,0.759325,0.835305,0.874145,0.553173,0.808139,1.000000

In [71]:
df_dummy = pd.get_dummies(data=df[['fueltype', 'aspiration', 'doornumber', 'carbody', 'drivewheel', 'enginelocation', 'enginetype', 'cylindernumber', 'fuelsystem', 'company']], drop_first = True)

In [72]:
df_dummy

,fueltype_gas,aspiration_turbo,doornumber_two,carbody_hardtop,carbody_hatchback,carbody_sedan,carbody_wagon,drivewheel_fwd,drivewheel_rwd,enginelocation_rear,...,company_nissan,company_peugeot,company_plymouth,company_porsche,company_renault,company_saab,company_subaru,company_toyota,company_volkswagen,company_volvo
0,True,False,True,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
1,True,False,True,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
2,True,False,True,False,True,False,False,False,True,False,...,False,False,False,False,False,False,False,False,False,False
3,True,False,False,False,False,True,False,True,False,False,...,False,False,False,False,False,False,False,False,False,False
4,True,False,False,False,False,True,False,False,False,False,...,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,True,False,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
201,True,True,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
202,True,False,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
203,False,True,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True
204,True,True,False,False,False,True,False,False,True,False,...,False,False,False,False,False,False,False,False,False,True

In [97]:
df_dummy_up = pd.get_dummies(data=up_df[['company', 'fueltype', 'aspiration','carbody', 'drivewheel', 'wheelbase', 'carlength','carwidth', 'curbweight', 'enginetype', 'cylindernumber', 'enginesize', 'boreratio','horsepower', 'price']], drop_first = True)

df_dummy_up = df_dummy_up.astype(int)

df_dummy_up

,wheelbase,carlength,carwidth,curbweight,enginesize,boreratio,horsepower,price,company_audi,company_bmw,...,enginetype_ohc,enginetype_ohcf,enginetype_ohcv,enginetype_rotor,cylindernumber_five,cylindernumber_four,cylindernumber_six,cylindernumber_three,cylindernumber_twelve,cylindernumber_two
0,88,168,64,2548,130,3,111,13495,0,0,...,0,0,0,0,0,1,0,0,0,0
1,88,168,64,2548,130,3,111,16500,0,0,...,0,0,0,0,0,1,0,0,0,0
2,94,171,65,2823,152,2,154,16500,0,0,...,0,0,1,0,0,0,1,0,0,0
3,99,176,66,2337,109,3,102,13950,1,0,...,1,0,0,0,0,1,0,0,0,0
4,99,176,66,2824,136,3,115,17450,1,0,...,1,0,0,0,1,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
200,109,188,68,2952,141,3,114,16845,0,0,...,1,0,0,0,0,1,0,0,0,0
201,109,188,68,3049,141,3,160,19045,0,0,...,1,0,0,0,0,1,0,0,0,0
202,109,188,68,3012,173,3,134,21485,0,0,...,0,0,1,0,0,0,1,0,0,0
203,109,188,68,3217,145,3,106,22470,0,0,...,1,0,0,0,0,0,1,0,0,0
204,109,188,68,3062,141,3,114,22625,0,0,...,1,0,0,0,0,1,0,0,0,0

In [75]:
# Предиктор (horsepower):
X = df_dummy_up['horsepower']

# Целевая переменная (price):
Y = df_dummy_up['price']

# Добавляем константу для учета пересечения (intercept) в модели:
X = sm.add_constant(X)

# Создаем и обучаем модель
model = sm.OLS(Y, X)
results = model.fit()

# Выводим результаты
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.653
Model:                            OLS   Adj. R-squared:                  0.651
Method:                 Least Squares   F-statistic:                     382.2
Date:                Sat, 27 Jul 2024   Prob (F-statistic):           1.48e-48
Time:                        11:36:44   Log-Likelihood:                -2024.0
No. Observations:                 205   AIC:                             4052.
Df Residuals:                     203   BIC:                             4059.
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
const      -3721.7615    929.849     -4.003      0.000   -5555.163   -1888.360
horsepower   163.2631      8.351     19.549      0.000     146.796     179.730
==============================================================================
Omnibus:                       47.741   Durbin-Watson:                   0.792
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               91.702
Skew:                           1.141   Prob(JB):                     1.22e-20
Kurtosis:                       5.352   Cond. No.                         314.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [98]:
# Предикторы:
Z = df_dummy_up.drop(['price'], axis = 'columns')

# Целевая переменная (price):
R = df_dummy_up['price']

# Добавляем константу для учета пересечения (intercept) в модели:
Z = sm.add_constant(Z)

# Создаем и обучаем модель
model = sm.OLS(R, Z)
results = model.fit()

# Выводим результаты
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.958
Model:                            OLS   Adj. R-squared:                  0.945
Method:                 Least Squares   F-statistic:                     77.51
Date:                Sat, 27 Jul 2024   Prob (F-statistic):           1.41e-87
Time:                        12:51:27   Log-Likelihood:                -1808.6
No. Observations:                 205   AIC:                             3711.
Df Residuals:                     158   BIC:                             3867.
Df Model:                          46
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                 -3.226e+04    1.2e+04     -2.696      0.008   -5.59e+04   -8624.965
wheelbase               142.4873     76.751      1.856      0.065      -9.102     294.077
carlength               -88.4933     51.631     -1.714      0.089    -190.470      13.484
carwidth                707.5606    222.608      3.179      0.002     267.889    1147.232
curbweight                3.8480      1.612      2.387      0.018       0.665       7.031
enginesize               25.7756     17.877      1.442      0.151      -9.533      61.084
boreratio              -963.4963    678.119     -1.421      0.157   -2302.844     375.851
horsepower               36.9248     18.306      2.017      0.045       0.769      73.080
company_audi           -437.6225   2141.766     -0.204      0.838   -4667.808    3792.563
company_bmw            6189.8338   1928.381      3.210      0.002    2381.104    9998.563
company_buick          2708.6439   2537.156      1.068      0.287   -2302.472    7719.760
company_chevrolet     -2704.1856   2071.964     -1.305      0.194   -6796.505    1388.134
company_dodge         -3911.9521   1652.234     -2.368      0.019   -7175.266    -648.638
company_honda         -3189.5476   1608.248     -1.983      0.049   -6365.986     -13.109
company_isuzu         -1733.7077   1808.770     -0.959      0.339   -5306.195    1838.779
company_jaguar         3648.0157   2595.904      1.405      0.162   -1479.133    8775.164
company_mazda         -2354.8224   1597.713     -1.474      0.143   -5510.452     800.807
company_mercury       -5118.6044   2640.359     -1.939      0.054   -1.03e+04      96.349
company_mitsubishi    -4706.2484   1610.080     -2.923      0.004   -7886.305   -1526.192
company_nissan        -2406.4952   1487.738     -1.618      0.108   -5344.914     531.924
company_peugeot        -649.2618   1732.224     -0.375      0.708   -4070.564    2772.040
company_plymouth      -3952.2197   1647.031     -2.400      0.018   -7205.257    -699.182
company_porsche        2930.7934   2639.976      1.110      0.269   -2283.402    8144.989
company_renault       -3948.8939   2022.545     -1.952      0.053   -7943.606      45.819
company_saab           -546.0541   1724.848     -0.317      0.752   -3952.787    2860.679
company_subaru        -1.288e+04   3319.606     -3.881      0.000   -1.94e+04   -6327.092
company_toyota        -3482.8889   1487.880     -2.341      0.020   -6421.589    -544.189
company_volkswagen    -2876.4611   1597.858     -1.800      0.074   -6032.377     279.455
company_volvo         -1747.0992   1776.413     -0.983      0.327   -5255.678    1761.479
fueltype_gas           -397.8394    929.984     -0.428      0.669   -2234.643    1438.964
aspiration_turbo        873.4308    717.098      1.218      0.225    -542.904    2289.765
carbody_hardtop       -2416.6206   1237.145     -1.953      0.053   -4860.096      26.855
carbody_hatchback     -2815.3423   1119.128     -2.516      0.013   -5025.723    -604.962
carbody_sedan         -2174.1312   1170.582     -1.857      0.065   -4486.139     137.877
carbody_wagon         -2761.5905   1240.025     -2.227      0.027   -5210.754    -312.427
drivewheel_fwd         -319.6144    914.553     -0.349      0.727   -2125.940    1486.711
drivewheel_rwd         -250.2190   1052.284     -0.238      0.812   -2328.577    1828.139
enginetype_dohcv      -1.116e+04   4238.893     -2.632      0.009   -1.95e+04   -2786.434
enginetype_l          -3330.2533   1420.921     -2.344      0.020   -6136.704    -523.803
enginetype_ohc          671.2708   1014.271      0.662      0.509   -1332.007    2674.549
enginetype_ohcf        9778.2683   2711.782      3.606      0.000    4422.250    1.51e+04
enginetype_ohcv       -2568.2875   1238.847     -2.073      0.040   -5015.124    -121.451
enginetype_rotor      -2887.4485   1703.763     -1.695      0.092   -6252.538     477.641
cylindernumber_five   -9716.8793   2312.358     -4.202      0.000   -1.43e+04   -5149.760
cylindernumber_four   -9474.1022   2806.908     -3.375      0.001    -1.5e+04   -3930.200
cylindernumber_six    -7883.5622   2512.461     -3.138      0.002   -1.28e+04   -2921.221
cylindernumber_three  -2680.9915   2458.246     -1.091      0.277   -7536.254    2174.271
cylindernumber_twelve -7545.3235   3705.572     -2.036      0.043   -1.49e+04    -226.478
cylindernumber_two    -2887.4485   1703.763     -1.695      0.092   -6252.538     477.641
==============================================================================
Omnibus:                       75.162   Durbin-Watson:                   1.362
Prob(Omnibus):                  0.000   Jarque-Bera (JB):              428.817
Skew:                           1.275   Prob(JB):                     7.65e-94
Kurtosis:                       9.611   Cond. No.                     1.02e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.35e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [99]:
#Выбираем колонки без марок машин:
cols_to_keep = df_dummy_up.columns[~ df_dummy_up.columns.str.startswith('company_')]
cols_to_keep

Index(['wheelbase', 'carlength', 'carwidth', 'curbweight', 'enginesize',
       'boreratio', 'horsepower', 'price', 'fueltype_gas', 'aspiration_turbo',
       'carbody_hardtop', 'carbody_hatchback', 'carbody_sedan',
       'carbody_wagon', 'drivewheel_fwd', 'drivewheel_rwd', 'enginetype_dohcv',
       'enginetype_l', 'enginetype_ohc', 'enginetype_ohcf', 'enginetype_ohcv',
       'enginetype_rotor', 'cylindernumber_five', 'cylindernumber_four',
       'cylindernumber_six', 'cylindernumber_three', 'cylindernumber_twelve',
       'cylindernumber_two'],
      dtype='object')

In [100]:
Z_2 = df_dummy_up[cols_to_keep].drop(['price'], axis = 'columns')

R_2 = df_dummy_up['price']

Z_2 = sm.add_constant(Z_2)

# Создаем и обучаем модель
model = sm.OLS(R_2, Z_2)
results = model.fit()

# Выводим результаты
print(results.summary())

                            OLS Regression Results
==============================================================================
Dep. Variable:                  price   R-squared:                       0.914
Model:                            OLS   Adj. R-squared:                  0.901
Method:                 Least Squares   F-statistic:                     72.46
Date:                Sat, 27 Jul 2024   Prob (F-statistic):           8.51e-81
Time:                        13:10:40   Log-Likelihood:                -1881.4
No. Observations:                 205   AIC:                             3817.
Df Residuals:                     178   BIC:                             3907.
Df Model:                          26
Covariance Type:            nonrobust
=========================================================================================
                            coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------------------------------------------------------
const                 -1.161e+04   1.26e+04     -0.923      0.357   -3.64e+04    1.32e+04
wheelbase                87.9002     85.804      1.024      0.307     -81.424     257.224
carlength               -45.4153     52.016     -0.873      0.384    -148.062      57.232
carwidth                415.0977    241.174      1.721      0.087     -60.831     891.026
curbweight                3.1057      1.790      1.735      0.084      -0.427       6.638
enginesize               23.3907     18.942      1.235      0.219     -13.988      60.770
boreratio             -1014.8759    677.562     -1.498      0.136   -2351.964     322.213
horsepower               83.3646     16.910      4.930      0.000      49.996     116.734
fueltype_gas          -2383.9537    979.991     -2.433      0.016   -4317.849    -450.059
aspiration_turbo       -933.2204    797.055     -1.171      0.243   -2506.113     639.672
carbody_hardtop       -3741.2763   1517.596     -2.465      0.015   -6736.072    -746.481
carbody_hatchback     -4775.1539   1295.547     -3.686      0.000   -7331.761   -2218.547
carbody_sedan         -3497.6606   1356.622     -2.578      0.011   -6174.792    -820.529
carbody_wagon         -4575.1937   1467.724     -3.117      0.002   -7471.573   -1678.815
drivewheel_fwd          252.6062   1126.063      0.224      0.823   -1969.544    2474.757
drivewheel_rwd         1479.4765   1206.158      1.227      0.222    -900.733    3859.686
enginetype_dohcv      -1.803e+04   4219.897     -4.274      0.000   -2.64e+04   -9706.571
enginetype_l           2124.9084   1328.400      1.600      0.111    -496.530    4746.347
enginetype_ohc         3983.3751    889.388      4.479      0.000    2228.273    5738.477
enginetype_ohcf        4578.6687   1149.646      3.983      0.000    2309.980    6847.357
enginetype_ohcv       -5232.3010   1294.335     -4.042      0.000   -7786.516   -2678.086
enginetype_rotor      -6309.4432   1702.900     -3.705      0.000   -9669.914   -2948.972
cylindernumber_five   -1.536e+04   2525.616     -6.082      0.000   -2.03e+04   -1.04e+04
cylindernumber_four   -1.849e+04   2545.234     -7.263      0.000   -2.35e+04   -1.35e+04
cylindernumber_six    -1.264e+04   2102.671     -6.011      0.000   -1.68e+04   -8490.681
cylindernumber_three  -1.272e+04   4018.833     -3.165      0.002   -2.06e+04   -4787.677
cylindernumber_twelve  -1.08e+04   3278.934     -3.293      0.001   -1.73e+04   -4326.717
cylindernumber_two    -6309.4432   1702.900     -3.705      0.000   -9669.914   -2948.972
==============================================================================
Omnibus:                       16.490   Durbin-Watson:                   1.270
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               41.368
Skew:                           0.272   Prob(JB):                     1.04e-09
Kurtosis:                       5.133   Cond. No.                     1.02e+16
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The smallest eigenvalue is 1.35e-23. This might indicate that there are
strong multicollinearity problems or that the design matrix is singular.

In [ ]:
#Выводы:

#Если судить чисто по диагностическим показателям (вроде R2), то модель со всеми предикторами лучшая.

#Большинство коэффициентов, связанных с марками машин, статистически незначимы.